### PR TITLE
Including record number as row-identifier, considering deleted ones

### PR DESCRIPTION
**Pull request by justusfowl**
In order to assess some kind of a row identifier, the field '@recordNumber' could be added that is also considering deletion flags.

### CODE REVIEW

**Comment by yortus** [comment]
Hi @justusfowl. Thanks for the PR. Can you give an example of what problem you are trying to solve with this row id, that is hard to do without it?

There are a couple of issues I can see. Eg, since the `readRecords` method works in chunks, it would mean two different records could have the same `@recordNumber` value, or the same record could have two different `@recordNumber` values, depending on the chunk size.

**Comment by justusfowl** [comment]
Hi @yortus , well - I am looking at a dbf file / table that does not have an application defined record Id. I am completely new to dbf - so I could be totally off - but my naive idea was that given the deletion flags, no record is actually removed from the file. So given FIFO we can just simply add an index to it. However, as I understood the current implementation, deleted records are not included in the recordset that is being read, correct? 

So the "row-index" should also include the rows that have an active deletion flag I hoped. 

Any suggestions are highly welcome :) thanks a lot!

**Comment by yortus** [comment]
Records marked as deleted are skipped over when reading records ([see here](https://github.com/yortus/DBFFile/blob/master/src/dbf-file.ts#L272-L273)), so the reader will not observe these records at all. Nor should it IMO, since this is just an format implementation detail, but logically speaking the record is no longer in the table.

Given that, do you still have a use case for this row id?

**Comment by justusfowl** [comment]
Yes exactly, thats why I thought to add and increment the recordId before skipping to add it to the output records set --> [see here](https://github.com/justusfowl/DBFFile/blob/716df28a10338c1e5b8626f59342ba996a2a1eb5/src/dbf-file.ts#L273)

My issue is that I need to have some unique id to a row that otherwise wouldn't be available - and I dont want to create a surrugate ID myself.

**Comment by yortus** [comment]
It sounds like what you are looking for is a way of detecting deleted records?

Can you give a little self-contained example of how you would use this? I'm just mindful that doing this at the library level affects all other library consumers, so I'd like to see what kind of problem is being solved.

Also, if you want a rowid that is unique to this row, consider the following example:
```ts
    let dbf = await DBFFile.open('<path to dbf file with 100s of records>');
    let rows0to99 = await dbf.readRecords(100);
    let rows100to199 = await dbf.readRecords(100);
    let row0 = rows0to99[0];
    let row100 = rows100to199[0];
    row0['@recordNumber']; // 0
    row100['@recordNumber']; // 0
```
is that the intent?

**Comment by justusfowl** [comment]
My use case is for reporting purposes, not transactional: Lets assume the example DBF that 

- contains a total of 260 records 
- of which 10 are deleted and 250 are not deleted, something along 
content of the file -> [
{@recordNumber : 0, @deleted : false,...},
{@recordNumber : 1, @deleted : false,...},
{@recordNumber : 2, @deleted : false,...},
{@recordNumber : 3, @deleted : **_true_**,...},
{@recordNumber : 4, @deleted : false,...},
{@recordNumber : 5, @deleted : false,...},
...
{@recordNumber : 259, @deleted : false,...}
]

I always want to read the entire file and process subsequently:

`
let dbf = await DBFFile.open('<path to dbf file with 260s of records>');
let allRowsThatAreNotDeleted = await dbf.readRecords();

row0['@recordNumber']; // 0
row4['@recordNumber']; // 4 (not 3, as the record with the recordNumber IN the file is deleted

// next step is doing some processing based on the @recordNumber in functions downstream my processing pipeline (along the lines of capturing IF there happend any changes per row 

`

I hope that makes it clearer, thank you!

**Comment by yortus** [comment]
So it looks like in your example, the library is (a) returning deleted rows to the caller, and (b) also adds a `@deleted` property. Is that right? Because currently neither (a) or (b) happens, even if this PR was merged.

> // next step is doing some processing based on the @recordNumber in functions downstream my processing pipeline (along the lines of capturing IF there happend any changes per row

Does this imply that some external process is actively still changing the contents of the table? In that case, the solution in this PR would not be reliable, since the external system may compact the records (eg using PACK) to remove all the deleted 'holes', which would change some or all of the rowids for existing records.

On the other hand, if you are absolutely sure that the external system will never physically move any existing records in the table, and you are always reading the entire set of records in a single call, then the `@recordNumber` is _always_ equal to the record's index in the array, so you can just write `rows.forEach((row, i) => { row['@recordNumber'] = i; })` in your own code.

**Comment by justusfowl** [comment]
Well - the @deleted flag was just for illustration purposes - the only thing I need is the actual number of the line of one row in the dbf file. 

The fact that another process is changing the file cannot be completely eradicated but it is the best guess that I have at this moment. Yet I assume that it does not since the dbf does contain very old records that have a deleted flag. That led me to believe that no row is actually removed by the 3rd party application and I could use the row-index as some sort of an identifier. 

To your last point: I was assuming that the deleted records are skipped in the output recordset (see [here](https://github.com/yortus/DBFFile/blob/master/src/dbf-file.ts#L272-L273) ). Which in turn will lead to the fact that the recordNumbers of the last row being output changes if the second to last record would have been deleted, right?

**Comment by justusfowl** [comment]
By the way: Thank you for taking the time to discuss this matter, very much appreciated!

**Comment by yortus** [comment]
There are some problems I see with this PR in it's current form that make it unsuitable as a general solution for all users of the library. Eg three qualities a rowid would have to have to be useful and reliable across various use cases:
* A rowid should be unique and stable per record, regardless of chunk size when reading
* A rowid should not change if records are physically moved (eg with PACK)
* A rowid should never clash with an existing field name

If the source table provides its own rowid for its records, then great. If not, I don't think there is a way for this library to provide one that works reliably in all circumstances, short of inserting one into the file, which is something a _reader_ cannot do. Since the library has diverse users and use cases, I'd rather not add something that only works in quite specific conditions, as in this PR.

I think the better solution to cover your use case would be to add an option for including deleted records in results when reading dbf files (off by default). Eg `DBFFile.open('filename', {includeDeletedRecords: true})`. Also, rather than adding an enumerable string property like `'@deleted'` to records, which could clash with a field name in the table, I'd prefer to use a unique symbol, and only include it in deleted records. Eg a returned set of rows might look like:
```ts
[
    {FNAME: 'alice', LNAME: 'brown'},
    {FNAME: 'bob', LNAME: 'smith', [DELETED]: true}, // where DELETED is a unique symbol exported from the library
    {FNAME: 'charles', LNAME: 'jones'}
]
```

What do you think?

**Comment by systolics** [comment]
That is a great idea - I will hopefully find some time during this week to work on it again and will file another PR then. 
Cheers!

**Comment by justusfowl** [comment]
That is a great idea - I will hopefully find some time during this week to work on it again and will file another PR then.
Cheers!

**Comment by yortus** [comment]
Hey @justusfowl, I've just published v1.6.0, which implements the `includeDeletedRecords` option as specified in https://github.com/yortus/DBFFile/pull/49#issuecomment-864111649.

Hopefully this solves the problem you were facing, let me know otherwise.

**Pull request closed without merging**
