### PR TITLE
Select encoding from parameter

### PR DESCRIPTION
**Pull request by mugan86**
Functionality that serves to manage the dbf files in the encoding that we choose. I was working with a DBF file that I had to work with, and this was in the "latin1" encoding, so characters like "ñ", "ª", ... were not displayed correctly since by default it only reads in utf8. 

Analyzing the library, I saw the possibility of adding it so that we can put it as a parameter due to my needs and I thought of contributing my little bit to this library that has been very useful for me ;)

### CODE REVIEW

**Comment by yortus** [comment]
Thanks @mugan86! This PR looks like a useful addition to the library.

There are a few changes I'd like to request first:
- [ ] since each dbf file has a single encoding, I think it makes more sense for the `encoding` parameter to be specified when opening or creating the file, i.e. in the `open` and `create` functions. Then there's no need to specify the encoding on each call to `append` and `readRecords`, and no possibility of trying to use several encodings with a single file.
- [ ] since more options may be added in future, I think I would be better to add an `options` parameter with `encoding` as an optional property. That way additional options can easily be added in future in a backward-compatible way. So for example: `open('path/to/file.dbf', {encoding: 'latin1'})`
- [ ] can you add a dbf file to the test fixtures that has `latin1` characters? The tests really need to demonstrate a case where the correct encoding matters to the test result.
- [ ] in the `README` file, remove the `maxRows = 10000000` and change back to `maxRows?: number`. This is just meant to be a type declaration for an optional parameter, whereas the specific initialiser is an implementation detail.

**Comment by mugan86** [comment]
- [ ] It seems logical to me what you mention of placing the encoding in the sections of creating and reading, but in cases like the one in my file (which I have had for a job that I have to do) it seems that it is badly formed, that is, the file is in utf8 but there are fields like the name that is in latin1, so applying those options only in the open and create file does not solve the problem and if you solve it by putting the selected encoding in the line with this code
`case 1:
                fd = _a.sent();
                rowsInBuffer = 1000;
                recordLength = dbf._recordLength;
                buffer = new Buffer(recordLength * rowsInBuffer);
                currentPosition = dbf._headerLength + recordLength * dbf._recordsRead;
                substr = function (start, count) { return buffer.toString(<ENCODING>, start, start + count); };
                rows = [];`
- [ ] The thing about setting a parameter to have different options such as encoding or possible new properties seems to me a fantastic idea, I like that idea and could implement it
- [ ] If I could add my file with latin1, the one I have has 7600 records but I reduce it to 4-5 records with "conflicting" data and we could add the tests related to that encoding.
- [ ] It is a good option to also leave it as optional

So, having the problem that I have told you that the file does not follow a specific encoding in all its columns, do I make the change based on it as well? I am waiting and when you confirm me, I will try to implement it as soon as possible.
Regards!

**Comment by yortus** [comment]
> the file is in utf8 but there are fields like the name that is in latin1

So a single record has different encodings in different fields? In that case I don't understand how selecting a single encoding in `readRecords` solves the problem. Won't you still need two different encodings to read the name field vs the other fields?

**Comment by yortus** [comment]
@mugan86 in V1.0, character encodings can now be specified either for a whole file, or per-field. There is no per-record option as implemented in this PR, but according to the comments here, it seems to me like the per-field option is actually what you needed.

**Pull request closed without merging**
