### PR TITLE
allow dbf files with version 0x31

### PR DESCRIPTION
**Pull request by anbraten**
I have a version 49 DBF file I wanted to read. 
By simply adding 0x31 to `src/file-version.ts` it worked for me from what I have tested.

### CODE REVIEW

**Comment by lordrip** [comment]
This looks nice :), do you think that could be possible to upload some fixtures and add a test in "reading-a-dbf-file#125"

like "description: 'VFP9 DBF with memo file (version 0x31)',"

**Comment by anbraten** [comment]
I have added a test with the `VFP9 DBF with auto-increment` file from [infused/dbf](https://github.com/infused/dbf/tree/master/spec/fixtures).
As that file has two new column types (currency & null-flags). I also added support for them.

**Comment by yortus** [comment]
Hi @anbraten, thanks for the PR, looks great so far. I'm just wondering about a few things this brings up:
- support for autoincrement fields (field type '+' I think?) - can we get read/write support in this PR? I can't find much info on them so not sure how they are supposed to work.
- could you add support for _writing_ as well as reading currency ('Y') fields?
- have you got a reference for the '0' null flags field type? I can't find anything on it.
- could you add test cases for writing as well as reading?
- could you tweak the README with the additional supported field types?

**Comment by anbraten** [comment]
@yortus I did some adjustments. Hope that helps. I would prefer to not implement new types in this PR to keep the changes "rather" small. Maybe opening a new issue / PR would be better? Whats your opinion? 

>  support for autoincrement fields (field type '+' I think?) - can we get read/write support in this PR? I can't find much info on them so not sure how they are supposed to work.

My files are using that version, but are without any real autoincrement fields. So I don't have anything to investigate how they really work and I couldn't find anything about them.

>  could you add support for writing as well as reading currency ('Y') fields?

Currency reading & writing should now be fully supported.

> have you got a reference for the '0' null flags field type? I can't find anything on it.

One library that seems to really support them is this python one: https://github.com/ethanfurman/dbf/blob/master/dbf/__init__.py

> could you add test cases for writing as well as reading?

I have added a test for writing as well.

> could you tweak the README with the additional supported field types?

Added the new column-types. Hope it to be like what you expected.

**Comment by yortus** [comment]
Keeping the PR small sounds fine, although in that case I feel like supporting 'VFP9 DBF with auto-increment' implies supporting autoincrement fields, and it is the currency and null flags that should probably go in a separate PR. I'm actually fine with a bigger PR, it's just the missing autoincrement support that seems problematic given that is what this PR is meant to address.

**Comment by yortus** [comment]
I'm wondering if another simple approach could work here. Since you mentioned this lib already works with your files once you added the `0x31` type, what about if the lib supported a 'loose reading mode' where it doesn't strictly validate the file version, and just tries to read the file? Loose mode could possibly also just skip over unrecognised field types instead of failing. Do you think that could work?

**Comment by anbraten** [comment]
> Keeping the PR small sounds fine, although in that case I feel like supporting 'VFP9 DBF with auto-increment' implies supporting autoincrement fields, and it is the currency and null flags that should probably go in a separate PR. I'm actually fine with a bigger PR, it's just the missing autoincrement support that seems problematic given that is what this PR is meant to address.

I agree on that. Calling it this way implies support for auto-increment. 
Same thing confused me a bit the first time I had a look at `infused/dbf` as they support version 0x31, but not auto-increment fields. So what is your suggestion to remove / change in this PR to not confuse others, but keep new features like the currency field?

> I'm wondering if another simple approach could work here. Since you mentioned this lib already works with your files once you added the 0x31 type, what about if the lib supported a 'loose reading mode' where it doesn't strictly validate the file version, and just tries to read the file? Loose mode could possibly also just skip over unrecognised field types instead of failing. Do you think that could work?

That sounds good to me. It would be probably quite simple to implement an option for that. Would you like me to create a new PR containing that option?

**Comment by yortus** [comment]
Hi @anbraten, as per https://github.com/yortus/DBFFile/pull/40#issuecomment-713329191 I'll close this PR too. However, would you like to slim it down to just the 'Y' field type support you added here? A PR that supports reading/writing 'Y' currency fields, with tests, would be awesome.

I'd prefer _not_ to add '0' null flags support - I actually think that one is _not_ a regular field type, but something called a _constraint_, so I'd rather leave it out unless somebody can figure out a full implementation that makes sense.

**Pull request closed without merging**
