### PR TITLE
Add support for read/write vfp dbf DateTime & Double data fields

### PR DESCRIPTION
**Pull request by lordrip**

### CODE REVIEW

**Comment by lordrip** [comment]
Hello @yortus, here's the PR for adding support to Visual FoxPro dbf with its DateTime fields & Double fields. Please forgive me and point it out if I've missed some styleguide of the project. Thanks in advanced!

**Comment by yortus** [comment]
Thanks @lordrip, great PR!

**Comment by lordrip** [comment]
Thanks to you for accepting it.

**Comment by lordrip** [comment]
Oh BTW, how this should work now? Should this be published to NPM? Or how can I get the recent changes from the PR directly?

**Comment by yortus** [comment]
I've published a new version to npm that includes your additions.

**Pull request merged**
